name: Test and Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Get dependencies
        run: go mod download

      - name: Run unit tests
        run: go test -v ./...

      - name: Run tests with coverage
        run: |
          go test -race -coverprofile=coverage.txt -covermode=atomic ./...
          go tool cover -func=coverage.txt

  build-linux-windows:
    name: Build Linux/Windows
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: windows
            arch: amd64
          - os: windows
            arch: arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Get dependencies
        run: go mod download

      - name: Build binary
        run: |
          mkdir -p dist
          
          if [ "${{ matrix.os }}" = "windows" ]; then
            # Build Windows binary with .exe extension
            GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o dist/summon-wpm-${{ matrix.os }}-${{ matrix.arch }}.exe -ldflags "-X main.version=$(grep "version = " cmd/summon-wpm/main.go | cut -d '"' -f2)" ./cmd/summon-wpm
          else
            # Build Linux binary
            GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o dist/summon-wpm-${{ matrix.os }}-${{ matrix.arch }} -ldflags "-X main.version=$(grep "version = " cmd/summon-wpm/main.go | cut -d '"' -f2)" ./cmd/summon-wpm
          fi

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: summon-wpm-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/summon-wpm-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.os == 'windows' && '.exe' || '' }}
          if-no-files-found: error

  build-macos:
    name: Build macOS Universal
    needs: test
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Get dependencies
        run: go mod download

      - name: Build universal macOS binary
        run: |
          mkdir -p dist
          
          # Build for Intel
          GOOS=darwin GOARCH=amd64 go build -o dist/summon-wpm-darwin-amd64 -ldflags "-X main.version=$(grep "version = " cmd/summon-wpm/main.go | cut -d '"' -f2)" ./cmd/summon-wpm
          
          # Build for Apple Silicon
          GOOS=darwin GOARCH=arm64 go build -o dist/summon-wpm-darwin-arm64 -ldflags "-X main.version=$(grep "version = " cmd/summon-wpm/main.go | cut -d '"' -f2)" ./cmd/summon-wpm
          
          # Create universal binary
          lipo -create -output dist/summon-wpm-darwin-universal dist/summon-wpm-darwin-amd64 dist/summon-wpm-darwin-arm64

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: summon-wpm-darwin-universal
          path: dist/summon-wpm-darwin-universal
          if-no-files-found: error